export {
  BUILDER_TEMPLATE_OPTIONS,
  DEFAULT_TEMPLATE_ID,
  TEMPLATE_CATEGORIES,
  TEMPLATE_CATEGORY_FILTERS,
  TEMPLATE_IDS,
  isRenderableTemplate,
  type BuilderTemplateOption,
  type TemplateCategory,
  type TemplateCategoryFilter,
  type TemplateCatalogId,
  type TemplateId,
} from "../domain/templates";

export {
  EMPTY_PERSONAL_INFO,
  getVisiblePersonalLinks,
  toExternalLinkHref,
  INITIAL_RESUME_DATA,
  PREVIEW_RESUME_DATA,
  normalizeEducationList,
  normalizeExperienceList,
  normalizeLinkList,
  normalizeProjectList,
  normalizeResumeData,
  normalizeResumeRecord,
  normalizeTemplateId,
  type ResumeData,
  type ResumeEducationItem,
  type ResumeExperienceItem,
  type ResumeLinkItem,
  type ResumePersonalInfo,
  type ResumeProjectItem,
  type ResumeRecord,
} from "../domain/resume";
